#############################################################################
# Makefile for building: P2kDoom
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  P2kDoom.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile P2kDoom.pro CONFIG+=release
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DRANGECHECK -DGBA -DP2K -DWORDS_BIGENDIAN
CFLAGS        = -pipe -O2 -g -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Iinc 
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)   -lSDL2 
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/am_map.c \
		src/d_client.c \
		src/d_items.c \
		src/d_main.c \
		src/f_finale.c \
		src/f_wipe.c \
		src/g_game.c \
		src/global_data.c \
		src/hu_lib.c \
		src/hu_stuff.c \
		src/i_audio.c \
		src/i_main.c \
		src/i_system.c \
		src/i_system_sdl2.c \
		src/i_video.c \
		src/info.c \
		src/lprintf.c \
		src/m_bbox.c \
		src/m_cheat.c \
		src/m_menu.c \
		src/m_random.c \
		src/m_recip.c \
		src/p_ceilng.c \
		src/p_doors.c \
		src/p_enemy.c \
		src/p_floor.c \
		src/p_genlin.c \
		src/p_inter.c \
		src/p_lights.c \
		src/p_map.c \
		src/p_maputl.c \
		src/p_mobj.c \
		src/p_plats.c \
		src/p_pspr.c \
		src/p_setup.c \
		src/p_sight.c \
		src/p_spec.c \
		src/p_switch.c \
		src/p_telept.c \
		src/p_tick.c \
		src/p_user.c \
		src/r_data.c \
		src/r_draw.c \
		src/r_hotpath.iwram.c \
		src/r_main.c \
		src/r_patch.c \
		src/r_plane.c \
		src/r_things.c \
		src/s_sound.c \
		src/sounds.c \
		src/st_gfx.c \
		src/st_lib.c \
		src/st_stuff.c \
		src/tables.c \
		src/v_video.c \
		src/version.c \
		src/w_memcache.c \
		src/w_wad.c \
		src/wi_stuff.c \
		src/z_bmalloc.c \
		src/z_zone.c 
OBJECTS       = am_map.o \
		d_client.o \
		d_items.o \
		d_main.o \
		f_finale.o \
		f_wipe.o \
		g_game.o \
		global_data.o \
		hu_lib.o \
		hu_stuff.o \
		i_audio.o \
		i_main.o \
		i_system.o \
		i_system_sdl2.o \
		i_video.o \
		info.o \
		lprintf.o \
		m_bbox.o \
		m_cheat.o \
		m_menu.o \
		m_random.o \
		m_recip.o \
		p_ceilng.o \
		p_doors.o \
		p_enemy.o \
		p_floor.o \
		p_genlin.o \
		p_inter.o \
		p_lights.o \
		p_map.o \
		p_maputl.o \
		p_mobj.o \
		p_plats.o \
		p_pspr.o \
		p_setup.o \
		p_sight.o \
		p_spec.o \
		p_switch.o \
		p_telept.o \
		p_tick.o \
		p_user.o \
		r_data.o \
		r_draw.o \
		r_hotpath.iwram.o \
		r_main.o \
		r_patch.o \
		r_plane.o \
		r_things.o \
		s_sound.o \
		sounds.o \
		st_gfx.o \
		st_lib.o \
		st_stuff.o \
		tables.o \
		v_video.o \
		version.o \
		w_memcache.o \
		w_wad.o \
		wi_stuff.o \
		z_bmalloc.o \
		z_zone.o
DESTDIR       = 
TARGET        = P2kDoom


first: all
####### Build rules

P2kDoom:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

all: P2kDoom

clean:
	-rm -Rf $(OBJECTS)
	-rm -Rf *~ core *.core
	-rm -Rf $(TARGET)

####### Sub-libraries

####### Compile

am_map.o: src/am_map.c inc/config.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/st_stuff.h \
		inc/d_event.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_setup.h \
		inc/p_maputl.h \
		inc/w_wad.h \
		inc/v_video.h \
		inc/p_spec.h \
		inc/am_map.h \
		inc/dstrings.h \
		inc/d_englsh.h \
		inc/lprintf.h \
		inc/g_game.h \
		inc/global_data.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o am_map.o src/am_map.c

d_client.o: src/d_client.c inc/config.h \
		inc/doomtype.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/d_net.h \
		inc/d_main.h \
		inc/d_event.h \
		inc/w_wad.h \
		inc/g_game.h \
		inc/m_menu.h \
		inc/protocol.h \
		inc/i_network.h \
		inc/i_system.h \
		inc/i_main.h \
		inc/i_video.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o d_client.o src/d_client.c

d_items.o: src/d_items.c inc/doomtype.h \
		inc/config.h \
		inc/info.h \
		inc/d_think.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o d_items.o src/d_items.c

d_main.o: src/d_main.c inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/doomtype.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/d_net.h \
		inc/dstrings.h \
		inc/d_englsh.h \
		inc/sounds.h \
		inc/w_wad.h \
		inc/s_sound.h \
		inc/r_defs.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/f_finale.h \
		inc/d_event.h \
		inc/f_wipe.h \
		inc/m_misc.h \
		inc/m_menu.h \
		inc/i_main.h \
		inc/i_system.h \
		inc/i_sound.h \
		inc/i_video.h \
		inc/g_game.h \
		inc/hu_stuff.h \
		inc/wi_stuff.h \
		inc/st_stuff.h \
		inc/am_map.h \
		inc/p_setup.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/d_main.h \
		inc/lprintf.h \
		inc/m_cheat.h \
		inc/doom_iwad.h \
		inc/global_data.h \
		inc/hu_lib.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o d_main.o src/d_main.c

f_finale.o: src/f_finale.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/d_event.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/w_wad.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/f_finale.h \
		inc/dstrings.h \
		inc/d_englsh.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o f_finale.o src/f_finale.c

f_wipe.o: src/f_wipe.c inc/config.h \
		inc/z_zone.h \
		inc/doomdef.h \
		inc/m_swap.h \
		inc/version.h \
		inc/i_video.h \
		inc/doomtype.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/m_fixed.h \
		inc/m_recip.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/tables.h \
		inc/doomdata.h \
		inc/info.h \
		inc/r_state.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/d_ticcmd.h \
		inc/r_patch.h \
		inc/m_random.h \
		inc/f_wipe.h \
		inc/global_data.h \
		inc/doomstat.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h \
		inc/i_system_e32.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o f_wipe.o src/f_wipe.c

g_game.o: src/g_game.c inc/config.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/d_net.h \
		inc/f_finale.h \
		inc/d_event.h \
		inc/m_misc.h \
		inc/m_menu.h \
		inc/m_random.h \
		inc/p_setup.h \
		inc/p_tick.h \
		inc/p_map.h \
		inc/r_defs.h \
		inc/d_main.h \
		inc/w_wad.h \
		inc/wi_stuff.h \
		inc/hu_stuff.h \
		inc/st_stuff.h \
		inc/am_map.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_draw.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/dstrings.h \
		inc/d_englsh.h \
		inc/r_sky.h \
		inc/p_inter.h \
		inc/g_game.h \
		inc/lprintf.h \
		inc/i_main.h \
		inc/i_system.h \
		inc/global_data.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/i_sound.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_maputl.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/gba_functions.h \
		inc/z_bmalloc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o g_game.o src/g_game.c

global_data.o: src/global_data.c inc/global_data.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/r_defs.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h \
		inc/global_init.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o global_data.o src/global_data.c

hu_lib.o: src/hu_lib.c inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/d_event.h \
		inc/r_main.h \
		inc/r_draw.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/g_game.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o hu_lib.o src/hu_lib.c

hu_stuff.o: src/hu_stuff.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/hu_stuff.h \
		inc/d_event.h \
		inc/hu_lib.h \
		inc/r_defs.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/dstrings.h \
		inc/d_englsh.h \
		inc/g_game.h \
		inc/r_main.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o hu_stuff.o src/hu_stuff.c

i_audio.o: src/i_audio.c inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/doomtype.h \
		inc/m_misc.h \
		inc/w_wad.h \
		inc/lprintf.h \
		inc/s_sound.h \
		inc/p_mobj.h \
		inc/tables.h \
		inc/m_fixed.h \
		inc/m_recip.h \
		inc/d_think.h \
		inc/doomdata.h \
		inc/info.h \
		inc/r_defs.h \
		inc/doomdef.h \
		inc/version.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/d_ticcmd.h \
		inc/d_main.h \
		inc/d_event.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/hu_stuff.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i_audio.o src/i_audio.c

i_main.o: src/i_main.c inc/config.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/d_main.h \
		inc/d_event.h \
		inc/doomtype.h \
		inc/w_wad.h \
		inc/m_fixed.h \
		inc/m_recip.h \
		inc/i_system.h \
		inc/i_video.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/tables.h \
		inc/doomdata.h \
		inc/info.h \
		inc/r_state.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/d_ticcmd.h \
		inc/r_patch.h \
		inc/lprintf.h \
		inc/m_random.h \
		inc/doomstat.h \
		inc/g_game.h \
		inc/m_misc.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/i_main.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i_main.o src/i_main.c

i_system.o: src/i_system.c inc/doomtype.h \
		inc/config.h \
		inc/m_fixed.h \
		inc/m_recip.h \
		inc/i_system.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/lprintf.h \
		inc/i_system_e32.h \
		inc/global_data.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/r_defs.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i_system.o src/i_system.c

i_system_sdl2.o: src/i_system_sdl2.c inc/doomtype.h \
		inc/config.h \
		inc/d_event.h \
		inc/d_main.h \
		inc/w_wad.h \
		inc/i_system_sdl2.h \
		inc/i_main.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i_system_sdl2.o src/i_system_sdl2.c

i_video.o: src/i_video.c inc/config.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_draw.h \
		inc/d_main.h \
		inc/d_event.h \
		inc/w_wad.h \
		inc/i_video.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/s_sound.h \
		inc/st_stuff.h \
		inc/lprintf.h \
		inc/i_system_e32.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o i_video.o src/i_video.c

info.o: src/info.c inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/sounds.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/p_mobj.h \
		inc/tables.h \
		inc/d_think.h \
		inc/doomdata.h \
		inc/info.h \
		inc/p_enemy.h \
		inc/p_pspr.h \
		inc/w_wad.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o info.o src/info.c

lprintf.o: src/lprintf.c inc/config.h \
		inc/doomtype.h \
		inc/lprintf.h \
		inc/i_main.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o lprintf.o src/lprintf.c

m_bbox.o: src/m_bbox.c inc/m_bbox.h \
		inc/m_fixed.h \
		inc/config.h \
		inc/doomtype.h \
		inc/m_recip.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o m_bbox.o src/m_bbox.c

m_cheat.o: src/m_cheat.c inc/m_cheat.h \
		inc/d_event.h \
		inc/doomtype.h \
		inc/config.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/d_englsh.h \
		inc/p_inter.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/g_game.h \
		inc/global_data.h \
		inc/doomstat.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/r_defs.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o m_cheat.o src/m_cheat.c

m_menu.o: src/m_menu.c inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/dstrings.h \
		inc/d_englsh.h \
		inc/d_main.h \
		inc/d_event.h \
		inc/w_wad.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_main.h \
		inc/hu_stuff.h \
		inc/g_game.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/m_misc.h \
		inc/lprintf.h \
		inc/am_map.h \
		inc/i_main.h \
		inc/i_system.h \
		inc/i_video.h \
		inc/i_sound.h \
		inc/global_data.h \
		inc/hu_lib.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o m_menu.o src/m_menu.c

m_random.o: src/m_random.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/m_random.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/r_defs.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o m_random.o src/m_random.c

m_recip.o: src/m_recip.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o m_recip.o src/m_recip.c

p_ceilng.o: src/p_ceilng.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_spec.h \
		inc/p_tick.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_ceilng.o src/p_ceilng.c

p_doors.o: src/p_doors.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/p_spec.h \
		inc/r_defs.h \
		inc/p_tick.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/dstrings.h \
		inc/d_englsh.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_doors.o src/p_doors.c

p_enemy.o: src/p_enemy.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/m_random.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_maputl.h \
		inc/p_map.h \
		inc/p_setup.h \
		inc/p_spec.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/p_inter.h \
		inc/g_game.h \
		inc/d_event.h \
		inc/p_enemy.h \
		inc/p_tick.h \
		inc/m_bbox.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_enemy.o src/p_enemy.c

p_floor.o: src/p_floor.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_map.h \
		inc/p_spec.h \
		inc/p_tick.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_maputl.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_floor.o src/p_floor.c

p_genlin.o: src/p_genlin.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_spec.h \
		inc/p_tick.h \
		inc/m_random.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_genlin.o src/p_genlin.c

p_inter.o: src/p_inter.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/dstrings.h \
		inc/d_englsh.h \
		inc/m_random.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/p_tick.h \
		inc/lprintf.h \
		inc/p_inter.h \
		inc/p_enemy.h \
		inc/global_data.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_inter.o src/p_inter.c

p_lights.o: src/p_lights.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/m_random.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_spec.h \
		inc/p_tick.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_lights.o src/p_lights.c

p_map.o: src/p_map.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_maputl.h \
		inc/p_map.h \
		inc/p_setup.h \
		inc/p_spec.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/p_inter.h \
		inc/m_random.h \
		inc/m_bbox.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h \
		inc/z_bmalloc.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_map.o src/p_map.c

p_maputl.o: src/p_maputl.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/m_bbox.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_maputl.h \
		inc/p_map.h \
		inc/p_setup.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_maputl.o src/p_maputl.c

p_mobj.o: src/p_mobj.c inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/m_random.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_maputl.h \
		inc/p_map.h \
		inc/p_tick.h \
		inc/sounds.h \
		inc/st_stuff.h \
		inc/d_event.h \
		inc/hu_stuff.h \
		inc/s_sound.h \
		inc/g_game.h \
		inc/p_inter.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_mobj.o src/p_mobj.c

p_plats.o: src/p_plats.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/m_random.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_spec.h \
		inc/p_tick.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_plats.o src/p_plats.c

p_pspr.o: src/p_pspr.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_map.h \
		inc/p_inter.h \
		inc/p_enemy.h \
		inc/m_random.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/d_event.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_pspr.o src/p_pspr.c

p_setup.o: src/p_setup.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/m_bbox.h \
		inc/g_game.h \
		inc/d_event.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_things.h \
		inc/r_draw.h \
		inc/p_maputl.h \
		inc/p_map.h \
		inc/p_setup.h \
		inc/p_spec.h \
		inc/p_tick.h \
		inc/p_enemy.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/lprintf.h \
		inc/v_video.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/r_plane.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_setup.o src/p_setup.c

p_sight.o: src/p_sight.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_setup.h \
		inc/m_bbox.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_sight.o src/p_sight.c

p_spec.o: src/p_spec.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/p_spec.h \
		inc/r_defs.h \
		inc/p_tick.h \
		inc/p_setup.h \
		inc/m_random.h \
		inc/d_englsh.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_maputl.h \
		inc/p_map.h \
		inc/g_game.h \
		inc/d_event.h \
		inc/p_inter.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/m_bbox.h \
		inc/r_plane.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/r_draw.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_spec.o src/p_spec.c

p_switch.o: src/p_switch.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_spec.h \
		inc/g_game.h \
		inc/d_event.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_switch.o src/p_switch.c

p_telept.o: src/p_telept.c inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/p_spec.h \
		inc/r_defs.h \
		inc/p_maputl.h \
		inc/p_map.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_tick.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/p_user.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_telept.o src/p_telept.c

p_tick.o: src/p_tick.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/p_user.h \
		inc/p_spec.h \
		inc/r_defs.h \
		inc/p_tick.h \
		inc/p_map.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_maputl.h \
		inc/r_draw.h \
		inc/r_main.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_tick.o src/p_tick.c

p_user.o: src/p_user.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/d_event.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/p_map.h \
		inc/p_spec.h \
		inc/p_user.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_enemy.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/w_wad.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o p_user.o src/p_user.c

r_data.o: src/r_data.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/w_wad.h \
		inc/r_draw.h \
		inc/r_defs.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_sky.h \
		inc/i_system.h \
		inc/r_things.h \
		inc/p_tick.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/r_plane.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o r_data.o src/r_data.c

r_draw.o: src/r_draw.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_draw.h \
		inc/v_video.h \
		inc/st_stuff.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/am_map.h \
		inc/lprintf.h \
		inc/gba_functions.h \
		inc/global_data.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o r_draw.o src/r_draw.c

r_hotpath.iwram.o: src/r_hotpath.iwram.c inc/config.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/d_net.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_things.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/m_bbox.h \
		inc/r_sky.h \
		inc/v_video.h \
		inc/lprintf.h \
		inc/st_stuff.h \
		inc/d_event.h \
		inc/i_main.h \
		inc/i_system.h \
		inc/g_game.h \
		inc/m_random.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/wi_stuff.h \
		inc/gba_functions.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o r_hotpath.iwram.o src/r_hotpath.iwram.c

r_main.o: src/r_main.c inc/config.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/d_net.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_things.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/m_bbox.h \
		inc/r_sky.h \
		inc/v_video.h \
		inc/lprintf.h \
		inc/st_stuff.h \
		inc/d_event.h \
		inc/i_main.h \
		inc/i_system.h \
		inc/g_game.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o r_main.o src/r_main.c

r_patch.o: src/r_patch.c inc/z_zone.h \
		inc/config.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_sky.h \
		inc/r_things.h \
		inc/r_draw.h \
		inc/p_tick.h \
		inc/i_system.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/r_plane.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o r_patch.o src/r_patch.c

r_plane.o: src/r_plane.c inc/config.h \
		inc/z_zone.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_draw.h \
		inc/r_things.h \
		inc/r_sky.h \
		inc/r_plane.h \
		inc/v_video.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h \
		inc/gba_functions.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o r_plane.o src/r_plane.c

r_things.o: src/r_things.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_segs.h \
		inc/r_draw.h \
		inc/r_things.h \
		inc/v_video.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_plane.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o r_things.o src/r_things.c

s_sound.o: src/s_sound.c inc/config.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/s_sound.h \
		inc/r_defs.h \
		inc/sounds.h \
		inc/i_sound.h \
		inc/i_system.h \
		inc/d_main.h \
		inc/d_event.h \
		inc/w_wad.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/m_random.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/v_video.h \
		inc/hu_stuff.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o s_sound.o src/s_sound.c

sounds.o: src/sounds.c inc/config.h \
		inc/doomtype.h \
		inc/sounds.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sounds.o src/sounds.c

st_gfx.o: src/st_gfx.c inc/stbar.h \
		inc/st_gfx.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o st_gfx.o src/st_gfx.c

st_lib.o: src/st_lib.c inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/w_wad.h \
		inc/st_stuff.h \
		inc/d_event.h \
		inc/st_lib.h \
		inc/r_main.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_draw.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/wi_stuff.h \
		inc/gba_functions.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o st_lib.o src/st_lib.c

st_stuff.o: src/st_stuff.c inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/m_random.h \
		inc/i_video.h \
		inc/v_video.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/w_wad.h \
		inc/st_stuff.h \
		inc/d_event.h \
		inc/st_lib.h \
		inc/r_main.h \
		inc/am_map.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/dstrings.h \
		inc/d_englsh.h \
		inc/r_draw.h \
		inc/global_data.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/wi_stuff.h \
		inc/st_gfx.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o st_stuff.o src/st_stuff.c

tables.o: src/tables.c inc/config.h \
		inc/w_wad.h \
		inc/tables.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o tables.o src/tables.c

v_video.o: src/v_video.c inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/r_main.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/r_draw.h \
		inc/m_bbox.h \
		inc/w_wad.h \
		inc/v_video.h \
		inc/i_video.h \
		inc/lprintf.h \
		inc/global_data.h \
		inc/doomstat.h \
		inc/am_map.h \
		inc/d_event.h \
		inc/g_game.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/sounds.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/s_sound.h \
		inc/st_lib.h \
		inc/st_stuff.h \
		inc/wi_stuff.h \
		inc/gba_functions.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o v_video.o src/v_video.c

version.o: src/version.c inc/version.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o version.o src/version.c

w_memcache.o: src/w_memcache.c inc/config.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/w_wad.h \
		inc/lprintf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o w_memcache.o src/w_memcache.c

w_wad.o: src/w_wad.c inc/config.h \
		inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/d_net.h \
		inc/i_system.h \
		inc/w_wad.h \
		inc/lprintf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o w_wad.o src/w_wad.c

wi_stuff.o: src/wi_stuff.c inc/doomstat.h \
		inc/d_player.h \
		inc/d_items.h \
		inc/doomdef.h \
		inc/config.h \
		inc/z_zone.h \
		inc/m_swap.h \
		inc/version.h \
		inc/p_pspr.h \
		inc/m_fixed.h \
		inc/doomtype.h \
		inc/m_recip.h \
		inc/tables.h \
		inc/info.h \
		inc/d_think.h \
		inc/p_mobj.h \
		inc/doomdata.h \
		inc/d_ticcmd.h \
		inc/m_random.h \
		inc/w_wad.h \
		inc/g_game.h \
		inc/d_event.h \
		inc/r_main.h \
		inc/r_data.h \
		inc/r_defs.h \
		inc/r_state.h \
		inc/r_patch.h \
		inc/v_video.h \
		inc/wi_stuff.h \
		inc/s_sound.h \
		inc/sounds.h \
		inc/lprintf.h \
		inc/r_draw.h \
		inc/global_data.h \
		inc/am_map.h \
		inc/hu_lib.h \
		inc/hu_stuff.h \
		inc/i_sound.h \
		inc/m_menu.h \
		inc/p_spec.h \
		inc/p_enemy.h \
		inc/p_map.h \
		inc/p_maputl.h \
		inc/p_tick.h \
		inc/r_plane.h \
		inc/r_things.h \
		inc/st_lib.h \
		inc/st_stuff.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wi_stuff.o src/wi_stuff.c

z_bmalloc.o: src/z_bmalloc.c inc/config.h \
		inc/doomtype.h \
		inc/z_zone.h \
		inc/z_bmalloc.h \
		inc/lprintf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o z_bmalloc.o src/z_bmalloc.c

z_zone.o: src/z_zone.c inc/z_zone.h \
		inc/config.h \
		inc/doomdef.h \
		inc/m_swap.h \
		inc/version.h \
		inc/doomtype.h \
		inc/lprintf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o z_zone.o src/z_zone.c

